---
name: Develop Frontend Nexter Website

on:
  push:
    branches-ignore:
      - release
      - main
      - develop

  pull_request:
    types: [opened, synchronize]

  workflow_dispatch:

jobs:
  build-frontend:
    name: Build Frontend Nexter Website
    runs-on: ubuntu-latest
    steps:
      - run: echo 'event name is:' ${{ github.event_name }}
      - run: echo 'event type is:' ${{ github.event.action }}
      - name: "ğŸ“¥  checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "ğŸ”  Verify Changed Frontend Nexter Website Files"
        uses: tj-actions/changed-files@v23.1
        id: changed-frontend-nexter-website-files
        with:
          files: |
              frontend/nexter-website/**/*
              frontend/living-style-guide/**/*.scss

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-frontend-nexter-website-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: "ğŸ”„  Cache node_modules"
        if: steps.changed-frontend-nexter-website-files.outputs.any_changed == 'true'
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: "ğŸ”§  Setup NodeJS 14.19.1"
        if: steps.changed-frontend-nexter-website-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: 14.19.1

      - name: "ğŸ”§  Install npm@latest"
        if: steps.changed-frontend-nexter-website-files.outputs.any_changed == 'true'
        run: npm i -g npm@latest

      - name: "ğŸ“¦  Install Frontend Nexter Website Development dependencies"
        if: steps.changed-frontend-nexter-website-files.outputs.any_changed == 'true'
        run: |
          bash scripts/install.bash

      - name: "ğŸ”  Lint Frontend Nexter Website"
        if: steps.changed-frontend-nexter-website-files.outputs.any_changed == 'true' && github.event_name == 'push'
        run: bash scripts/frontend-nexter-website-lint.bash

      - name: 'ğŸ§ª  Test Frontend Living Style Guide'
        if: steps.changed-frontend-nexter-website-files.outputs.any_changed == 'true' && github.event_name == 'push'
        run: bash scripts/frontend-living-style-guide-test.bash

      - name: "ğŸ—ï¸  Build Frontend Nexter Website"
        if: steps.changed-frontend-nexter-website-files.outputs.any_changed == 'true' && github.event_name == 'pull_request'
        run: |
          bash scripts/assets-process.bash
          bash scripts/frontend-nexter-website-build.bash production